[build]
buildCommand = "cd server && npm ci --only=production --ignore-scripts"

[deploy]
startCommand = "cd server && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/health"
healthcheckTimeout = 300
watchPatterns = ["server/**"]

[env]
NODE_ENV = "production"
PORT = "5000"